export const sampleTags = [
    'Pet toys',
    'Pets',
    'Toys',
    'Pet health',
    'Accessories',
    'Pet care',
    'family and pets',
    'Pet nutrition',
    'Pet fashion and accessories'
];

export const fallbackImage = "https://res.cloudinary.com/dta662hjr/image/upload/v1715681470/pet-store/other/image_ilcavg.jpg"
export const weightUnit = [
    {"value": "g", "name": "gram"},
    {"value": "kg", "name": "kilogram"},
    {"value": "lb", "name": "pound"},
    {"value": "oz", "name": "ounce"}
]


export const countries =
    [
        {"value": "AF", "name": "Afghanistan"},
        {"value": "AX", "name": "Åland Islands"},
        {"value": "AL", "name": "Albania"},
        {"value": "DZ", "name": "Algeria"},
        {"value": "AD", "name": "Andorra"},
        {"value": "AO", "name": "Angola"},
        {"value": "AI", "name": "Anguilla"},
        {"value": "AG", "name": "Antigua & Barbuda"},
        {"value": "AR", "name": "Argentina"},
        {"value": "AM", "name": "Armenia"},
        {"value": "AW", "name": "Aruba"},
        {"value": "AC", "name": "Ascension Island"},
        {"value": "AU", "name": "Australia"},
        {"value": "AT", "name": "Austria"},
        {"value": "AZ", "name": "Azerbaijan"},
        {"value": "BS", "name": "Bahamas"},
        {"value": "BH", "name": "Bahrain"},
        {"value": "BD", "name": "Bangladesh"},
        {"value": "BB", "name": "Barbados"},
        {"value": "BY", "name": "Belarus"},
        {"value": "BE", "name": "Belgium"},
        {"value": "BZ", "name": "Belize"},
        {"value": "BJ", "name": "Benin"},
        {"value": "BM", "name": "Bermuda"},
        {"value": "BT", "name": "Bhutan"},
        {"value": "BO", "name": "Bolivia"},
        {"value": "BA", "name": "Bosnia & Herzegovina"},
        {"value": "BW", "name": "Botswana"},
        {"value": "BR", "name": "Brazil"},
        {"value": "IO", "name": "British Indian Ocean Territory"},
        {"value": "VG", "name": "British Virgin Islands"},
        {"value": "BN", "name": "Brunei"},
        {"value": "BG", "name": "Bulgaria"},
        {"value": "BF", "name": "Burkina Faso"},
        {"value": "BI", "name": "Burundi"},
        {"value": "KH", "name": "Cambodia"},
        {"value": "CM", "name": "Cameroon"},
        {"value": "CA", "name": "Canada"},
        {"value": "CV", "name": "Cape Verde"},
        {"value": "BQ", "name": "Caribbean Netherlands"},
        {"value": "KY", "name": "Cayman Islands"},
        {"value": "CF", "name": "Central African Republic"},
        {"value": "TD", "name": "Chad"},
        {"value": "CL", "name": "Chile"},
        {"value": "CN", "name": "China"},
        {"value": "CX", "name": "Christmas Island"},
        {"value": "CC", "name": "Cocos (Keeling) Islands"},
        {"value": "CO", "name": "Colombia"},
        {"value": "KM", "name": "Comoros"},
        {"value": "CG", "name": "Congo - Brazzaville"},
        {"value": "CD", "name": "Congo - Kinshasa"},
        {"value": "CK", "name": "Cook Islands"},
        {"value": "CR", "name": "Costa Rica"},
        {"value": "HR", "name": "Croatia"},
        {"value": "CW", "name": "Curaçao"},
        {"value": "CY", "name": "Cyprus"},
        {"value": "CZ", "name": "Czechia"},
        {"value": "CI", "name": "Côte d’Ivoire"},
        {"value": "DK", "name": "Denmark"},
        {"value": "DJ", "name": "Djibouti"},
        {"value": "DM", "name": "Dominica"},
        {"value": "DO", "name": "Dominican Republic"},
        {"value": "EC", "name": "Ecuador"},
        {"value": "EG", "name": "Egypt"},
        {"value": "SV", "name": "El Salvador"},
        {"value": "GQ", "name": "Equatorial Guinea"},
        {"value": "ER", "name": "Eritrea"},
        {"value": "EE", "name": "Estonia"},
        {"value": "SZ", "name": "Eswatini"},
        {"value": "ET", "name": "Ethiopia"},
        {"value": "FK", "name": "Falkland Islands"},
        {"value": "FO", "name": "Faroe Islands"},
        {"value": "FJ", "name": "Fiji"},
        {"value": "FI", "name": "Finland"},
        {"value": "FR", "name": "France"},
        {"value": "GF", "name": "French Guiana"},
        {"value": "PF", "name": "French Polynesia"},
        {"value": "TF", "name": "French Southern Territories"},
        {"value": "GA", "name": "Gabon"},
        {"value": "GM", "name": "Gambia"},
        {"value": "GE", "name": "Georgia"},
        {"value": "DE", "name": "Germany"},
        {"value": "GH", "name": "Ghana"},
        {"value": "GI", "name": "Gibraltar"},
        {"value": "GR", "name": "Greece"},
        {"value": "GL", "name": "Greenland"},
        {"value": "GD", "name": "Grenada"},
        {"value": "GP", "name": "Guadeloupe"},
        {"value": "GT", "name": "Guatemala"},
        {"value": "GG", "name": "Guernsey"},
        {"value": "GN", "name": "Guinea"},
        {"value": "GW", "name": "Guinea-Bissau"},
        {"value": "GY", "name": "Guyana"},
        {"value": "HT", "name": "Haiti"},
        {"value": "HN", "name": "Honduras"},
        {"value": "HK", "name": "Hong Kong SAR"},
        {"value": "HU", "name": "Hungary"},
        {"value": "IS", "name": "Iceland"},
        {"value": "IN", "name": "India"},
        {"value": "ID", "name": "Indonesia"},
        {"value": "IQ", "name": "Iraq"},
        {"value": "IE", "name": "Ireland"},
        {"value": "IM", "name": "Isle of Man"},
        {"value": "IL", "name": "Israel"},
        {"value": "IT", "name": "Italy"},
        {"value": "JM", "name": "Jamaica"},
        {"value": "JP", "name": "Japan"},
        {"value": "JE", "name": "Jersey"},
        {"value": "JO", "name": "Jordan"},
        {"value": "KZ", "name": "Kazakhstan"},
        {"value": "KE", "name": "Kenya"},
        {"value": "KI", "name": "Kiribati"},
        {"value": "XK", "name": "Kosovo"},
        {"value": "KW", "name": "Kuwait"},
        {"value": "KG", "name": "Kyrgyzstan"},
        {"value": "LA", "name": "Laos"},
        {"value": "LV", "name": "Latvia"},
        {"value": "LB", "name": "Lebanon"},
        {"value": "LS", "name": "Lesotho"},
        {"value": "LR", "name": "Liberia"},
        {"value": "LY", "name": "Libya"},
        {"value": "LI", "name": "Liechtenstein"},
        {"value": "LT", "name": "Lithuania"},
        {"value": "LU", "name": "Luxembourg"},
        {"value": "MO", "name": "Macao SAR"},
        {"value": "MG", "name": "Madagascar"},
        {"value": "MW", "name": "Malawi"},
        {"value": "MY", "name": "Malaysia"},
        {"value": "MV", "name": "Maldives"},
        {"value": "ML", "name": "Mali"},
        {"value": "MT", "name": "Malta"},
        {"value": "MQ", "name": "Martinique"},
        {"value": "MR", "name": "Mauritania"},
        {"value": "MU", "name": "Mauritius"},
        {"value": "YT", "name": "Mayotte"},
        {"value": "MX", "name": "Mexico"},
        {"value": "MD", "name": "Moldova"},
        {"value": "MC", "name": "Monaco"},
        {"value": "MN", "name": "Mongolia"},
        {"value": "ME", "name": "Montenegro"},
        {"value": "MS", "name": "Montserrat"},
        {"value": "MA", "name": "Morocco"},
        {"value": "MZ", "name": "Mozambique"},
        {"value": "MM", "name": "Myanmar (Burma)"},
        {"value": "NA", "name": "Namibia"},
        {"value": "NR", "name": "Nauru"},
        {"value": "NP", "name": "Nepal"},
        {"value": "NL", "name": "Netherlands"},
        {"value": "NC", "name": "New Caledonia"},
        {"value": "NZ", "name": "New Zealand"},
        {"value": "NI", "name": "Nicaragua"},
        {"value": "NE", "name": "Niger"},
        {"value": "NG", "name": "Nigeria"},
        {"value": "NU", "name": "Niue"},
        {"value": "NF", "name": "Norfolk Island"},
        {"value": "MK", "name": "North Macedonia"},
        {"value": "NO", "name": "Norway"},
        {"value": "OM", "name": "Oman"},
        {"value": "PK", "name": "Pakistan"},
        {"value": "PS", "name": "Palestinian Territories"},
        {"value": "PA", "name": "Panama"},
        {"value": "PG", "name": "Papua New Guinea"},
        {"value": "PY", "name": "Paraguay"},
        {"value": "PE", "name": "Peru"},
        {"value": "PH", "name": "Philippines"},
        {"value": "PN", "name": "Pitcairn Islands"},
        {"value": "PL", "name": "Poland"},
        {"value": "PT", "name": "Portugal"},
        {"value": "QA", "name": "Qatar"},
        {"value": "RE", "name": "Réunion"},
        {"value": "RO", "name": "Romania"},
        {"value": "RU", "name": "Russia"},
        {"value": "RW", "name": "Rwanda"},
        {"value": "WS", "name": "Samoa"},
        {"value": "SM", "name": "San Marino"},
        {"value": "ST", "name": "São Tomé & Príncipe"},
        {"value": "SA", "name": "Saudi Arabia"},
        {"value": "SN", "name": "Senegal"},
        {"value": "RS", "name": "Serbia"},
        {"value": "SC", "name": "Seychelles"},
        {"value": "SL", "name": "Sierra Leone"},
        {"value": "SG", "name": "Singapore"},
        {"value": "SX", "name": "Sint Maarten"},
        {"value": "SK", "name": "Slovakia"},
        {"value": "SI", "name": "Slovenia"},
        {"value": "SB", "name": "Solomon Islands"},
        {"value": "SO", "name": "Somalia"},
        {"value": "ZA", "name": "South Africa"},
        {"value": "GS", "name": "South Georgia & South Sandwich Islands"},
        {"value": "KR", "name": "South Korea"},
        {"value": "SS", "name": "South Sudan"},
        {"value": "ES", "name": "Spain"},
        {"value": "LK", "name": "Sri Lanka"},
        {"value": "BL", "name": "St. Barthélemy"},
        {"value": "SH", "name": "St. Helena"},
        {"value": "KN", "name": "St. Kitts & Nevis"},
        {"value": "LC", "name": "St. Lucia"},
        {"value": "MF", "name": "St. Martin"},
        {"value": "PM", "name": "St. Pierre & Miquelon"},
        {"value": "VC", "name": "St. Vincent & Grenadines"},
        {"value": "SD", "name": "Sudan"},
        {"value": "SR", "name": "Suriname"},
        {"value": "SJ", "name": "Svalbard & Jan Mayen"},
        {"value": "SE", "name": "Sweden"},
        {"value": "CH", "name": "Switzerland"},
        {"value": "TW", "name": "Taiwan"},
        {"value": "TJ", "name": "Tajikistan"},
        {"value": "TZ", "name": "Tanzania"},
        {"value": "TH", "name": "Thailand"},
        {"value": "TL", "name": "Timor-Leste"},
        {"value": "TG", "name": "Togo"},
        {"value": "TK", "name": "Tokelau"},
        {"value": "TO", "name": "Tonga"},
        {"value": "TT", "name": "Trinidad & Tobago"},
        {"value": "TA", "name": "Tristan da Cunha"},
        {"value": "TN", "name": "Tunisia"},
        {"value": "TR", "name": "Türkiye"},
        {"value": "TM", "name": "Turkmenistan"},
        {"value": "TC", "name": "Turks & Caicos Islands"},
        {"value": "TV", "name": "Tuvalu"},
        {"value": "UM", "name": "U.S. Outlying Islands"},
        {"value": "UG", "name": "Uganda"},
        {"value": "UA", "name": "Ukraine"},
        {"value": "AE", "name": "United Arab Emirates"},
        {"value": "GB", "name": "United Kingdom"},
        {"value": "US", "name": "United States"},
        {"value": "UY", "name": "Uruguay"},
        {"value": "UZ", "name": "Uzbekistan"},
        {"value": "VU", "name": "Vanuatu"},
        {"value": "VA", "name": "Vatican City"},
        {"value": "VE", "name": "Venezuela"},
        {"value": "VN", "name": "Vietnam"},
        {"value": "WF", "name": "Wallis & Futuna"},
        {"value": "EH", "name": "Western Sahara"},
        {"value": "YE", "name": "Yemen"},
        {"value": "ZM", "name": "Zambia"},
        {"value": "ZW", "name": "Zimbabwe"}
    ];


export const rawCollection = [] as any[]    ;
for(let i = 0; i< 20; i++){
        rawCollection.push({
                id: `${i+1}`,
                name: `Collection ${i+1}`
        });
}


export const  sampleOption = ['Color', 'Size', 'Material', "Type"]


export const userOrderData = [
        {
                id: '802e1c98f6ec45a6851619293e67cf9b',
                code: "G-252797",
                products:[
                        {
                                _id: "sp1",
                                name: "Áo thun Việt Nam trong tim tôi - Đen / XXL",
                                code:"ANVNNS",
                                price: 199000,
                                quantity:1,
                                totalPrice:199000
                        },
                        {
                                _id: "sp2",
                                name: "Áo thun tay ngắn Dòng máu Lạc Hồng - Âu Cơ // Trắng - Trắng / XXL",
                                code:"ANAUCO",
                                price: 169000,
                                quantity:1,
                                totalPrice:169000
                        },
                        {
                                _id: "sp2",
                                name: "Áo thun tay dài Dòng máu Lạc Hồng - Âu Cơ // Trắng - Trắng / XXL",
                                code:"ADAUCO",
                                price: 169000,
                                quantity:1,
                                totalPrice:169000
                        }
                ],
                temp_price: 537000,
                shipping_fee: 40000,
                total_price:437000,
                orderDate: " 06/13/2024 01:45:58",
                cancelDate: "06/13/2024 11:12SA",
                cancelReason:" Khách hàng đổi ý",
                paymentStatus:"PENDING",
                fulfillmentStatus:"not fulfilled",
                user_shipping:{
                        name:"Trịnh Phương Thảo",
                        phone: "0327072255",
                        address:"bia hơi Bích Triệu, tổ dân phố 15,\n"
                },
                status: "CANCELLED"
        },
        {
                id: '50751b590bca47618ed1c4af08ed7488',
                code: "G-250848",
                status: "COMPLETED",
                products:[
                        {
                                _id: "sp1",
                                name: "Áo thun Grimm DC raccoon | đen - Đen / XL",
                                code:"ANRACCOON",
                                price: 199000,
                                quantity:1,
                                totalPrice:199000
                        }
                ],
                temp_price: 199000,
                shipping_fee: 35000,
                total_price:229000,
                orderDate: " 04/28/2024 05:33:54",
                cancelDate: null,
                cancelReason:null,
                paymentStatus:"PAID",
                fulfillmentStatus:"FULFILLED",
                user_shipping:{
                        name:"Trịnh Phương Thảo",
                        phone: "0327072255",
                        address:"bia hơi Bích Triệu, tổ dân phố 15,\n"
                }
        },
        {
                id: '802e1c98f6ec45a6851619293e67cf9c',
                code: "G-2527201",
                products:[
                        {
                                _id: "sp435",
                                name: "Nón Grimmm DC Raccoon\n",
                                code:"NTRACCOON",
                                price: 119000,
                                quantity:1,
                                totalPrice:199000
                        },
                        {
                                _id: "sp1",
                                name: "Áo thun Việt Nam trong tim tôi - Đen / XXL",
                                code:"ANVNNS",
                                price: 199000,
                                quantity:1,
                                totalPrice:199000
                        },
                        {
                                _id: "sp2",
                                name: "Áo thun tay ngắn Dòng máu Lạc Hồng - Âu Cơ // Trắng - Trắng / XXL",
                                code:"ANAUCO",
                                price: 169000,
                                quantity:2,
                                totalPrice:169000
                        },
                        {
                                _id: "sp2",
                                name: "Áo thun tay dài Dòng máu Lạc Hồng - Âu Cơ // Trắng - Trắng / XXL",
                                code:"ADAUCO",
                                price: 169000,
                                quantity:1,
                                totalPrice:169000
                        }
                ],
                temp_price: 706000,
                shipping_fee: 40000,
                total_price:737000,
                orderDate: " 06/17/2024 01:45:58",
                cancelDate:null,
                cancelReason:null,
                paymentStatus:"PENDING",
                fulfillmentStatus:"NOT_FULFILLED",
                user_shipping:{
                        name:"Trịnh Phương Thảo",
                        phone: "0327072255",
                        address:"bia hơi Bích Triệu, tổ dân phố 15,\n"
                },
                status: "PENDING"
        },
];


export const vouchers = [

]