import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "react-hot-toast";
import * as React from "react";
import "./globals.css";


const lexend = Lexend({
    subsets: ['latin'],
    display: 'swap',
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={lexend.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <React.Fragment>
                        {children}
                        <Toaster />
                    </React.Fragment>
                </ThemeProvider>
            </body>
        </html>
    );
}
